name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Deploy only when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build
        

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Install mkdocs material
        run: pip install mkdocs-material

      - name: Build MkDocs into React build folder
        run: mkdocs build -d build/docs -f ./mkdocs/mkdocs.yml


      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
