site_name: 4DGeo
repo_url: https://github.com/3dgeo-heidelberg/4dgeo
docs_dir: ../docs
site_dir: ../build/docs
site_url: https://3dgeo-heidelberg.github.io/4dgeo/docs/

theme:
  logo: img/3DGeo_globe_white.svg     # light mode logo
  favicon: img/3dgeo.ico
  name: material
  custom_dir: overrides
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        logo: img/3DGeo_globe_white.svg     # light mode logo
        primary: custom
        accent: custom
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        logo: img/3DGeo_globe_red.png     # dark mode logo
        primary: custom
        accent: custom  # same as above
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.footer
use_directory_urls: false
extra_css:
  - customs.css
  - style.css
plugins:
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: true
      ignore_h1_titles: True
  - search
markdown_extensions:
  - attr_list
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Application: Application.md
  - Notebook examples:
    - Main AImon5.0 monitoring pipeline: main.ipynb
    - Adaptive monitoring: adaptive_monitoring.ipynb
    - Rule-based classification of change events: classification_of_change_events_rule_based.ipynb
    - Rule-based filtering of change events: filtering_of_change_events_rule_based.ipynb
    - Random forest classification of change events: classification_of_change_events_using_random_forest_classifier.ipynb
    - Configuration description: configuration_description.md